In [4]:
import pandas as pd
from sklearn import linear_model

In [60]:
df=pd.read_csv('mutiple value.csv')

In [62]:
df

   Age  Height  Weight  Premium
0   25  162.56      70    18000
1   30  172.72      95    38000
2   35  167.64      78    38000
3   40     NaN     110    60000
4   45  157.48      85    70000

In [64]:
#reaplace missing varable
mean_height=df.Height.mean()

In [66]:
df.Height=df.Height.fillna(mean_height)

In [68]:
df

   Age  Height  Weight  Premium
0   25  162.56      70    18000
1   30  172.72      95    38000
2   35  167.64      78    38000
3   40  165.10     110    60000
4   45  157.48      85    70000

In [70]:
reg=linear_model.LinearRegression()

In [80]:
reg.fit(df[['Age','Height','Weight']].values,df[['Premium']].values)

LinearRegression()

In [82]:
reg.coef_

array([[2150.26052416, -248.45851574,  312.65291961]])

In [84]:
reg.intercept_

array([-16827.01315482])

In [88]:
reg.predict([[27,167,60]])

array([[18496.62404572]])

In [90]:
# cross check y=m1*x1+m2*x2----+c
27*2150.26052416+167*-248.45851574+60*312.65291961-16827.01315482

18496.624045519995

In [92]:
reg.predict([[60,187,90]])

array([[93865.63861639]])